import type { Metadata } from 'next';
import { Plus_Jakarta_Sans } from 'next/font/google';
import '@/ui/shared/styles/globals.css';
import { ShadcnSidebarProvider } from '@/ui/shadcn/sidebar';
import { Sidebar } from '@/ui/sidebar/components/sidebar';
import { getAllBoardsUseCase } from '@/main/dependencies';

const jakarta = Plus_Jakarta_Sans({
  variable: '--font-jakarta',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Kanban App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const boards = await getAllBoardsUseCase();

  return (
    <html lang='en'>
      <body
        className={`${jakarta.variable} antialiased font-jakarta bg-light-grey dark:bg-very-dark-grey`}
      >
        <ShadcnSidebarProvider>
          <Sidebar items={boards} className='hidden lg:block' />
          {children}
        </ShadcnSidebarProvider>
      </body>
    </html>
  );
}
